/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        // 竹青 — 太极能量/成长色 (柔和冷色，平衡暖色 primary)
        bamboo: {
          50: "#f2f7ed",
          100: "#e0efd3",
          200: "#c2dfa7",
          300: "#9fcc77",
          400: "#7fb84f",
          500: "#5a8f4a",
          600: "#4a7a3d",
          700: "#3d6b30",
          800: "#2f5425",
          900: "#1e3a17",
        },
        // 水墨灰 — 等级/精通色 (暖调近黑)
        ink: {
          50: "#f5f5f4",
          100: "#e8e6e3",
          200: "#d1cdc7",
          300: "#b3ada3",
          400: "#958e80",
          500: "#2c2c2c",
          600: "#242424",
          700: "#1c1c1c",
          800: "#141414",
          900: "#0a0a0a",
        },
        "on-tertiary-fixed-variant": "#484741",
        "on-tertiary-fixed": "#1c1c17",
        "on-secondary-container": "#3c6c6e",
        "outline-variant": "#dac2b4",
        "primary-fixed-dim": "#ffb68a",
        "on-primary": "#ffffff",
        "on-primary-container": "#743500",
        error: "#ba1a1a",
        "on-surface": "#1b1c1c",
        "on-secondary-fixed-variant": "#1a4e50",
        background: "#fcf9f8",
        "primary-container": "#ff9d5c",
        "primary-fixed": "#ffdbc8",
        "tertiary-fixed": "#e6e2d9",
        "on-background": "#1b1c1c",
        "on-error": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "inverse-primary": "#ffb68a",
        "on-tertiary-container": "#484741",
        "tertiary-fixed-dim": "#c9c6be",
        "surface-tint": "#95490d",
        secondary: "#356668",
        "surface-variant": "#e4e2e1",
        "on-primary-fixed-variant": "#743500",
        "secondary-fixed": "#b9ecee",
        "surface-container": "#f0eded",
        "surface-container-highest": "#e4e2e1",
        "surface-container-low": "#f6f3f2",
        "on-tertiary": "#ffffff",
        "surface-bright": "#fcf9f8",
        tertiary: "#605e58",
        "on-secondary": "#ffffff",
        "inverse-on-surface": "#f3f0f0",
        "on-error-container": "#93000a",
        "surface-dim": "#dcd9d9",
        "on-secondary-fixed": "#002021",
        primary: "#95490d",
        "on-primary-fixed": "#321300",
        "inverse-surface": "#303030",
        surface: "#fcf9f8",
        "error-container": "#ffdad6",
        "on-surface-variant": "#544339",
        "secondary-fixed-dim": "#9ecfd1",
        "secondary-container": "#b9ecee",
        "surface-container-high": "#eae7e7",
        outline: "#877368",
        "tertiary-container": "#b8b5ad",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      spacing: {
        "stack-lg": "24px",
        "margin-mobile": "20px",
        unit: "4px",
        "stack-sm": "8px",
        "stack-md": "16px",
        gutter: "12px",
      },
      fontFamily: {
        "headline-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-xl": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Be Vietnam Pro", "sans-serif"],
        "body-md": ["Be Vietnam Pro", "sans-serif"],
      },
      fontSize: {
        "headline-lg-mobile": [
          "22px",
          { lineHeight: "28px", fontWeight: "700" },
        ],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "700" }],
        "label-md": ["14px", { lineHeight: "20px", fontWeight: "600" }],
        "headline-xl": [
          "32px",
          {
            lineHeight: "40px",
            letterSpacing: "-0.02em",
            fontWeight: "800",
          },
        ],
        "headline-lg": [
          "24px",
          {
            lineHeight: "32px",
            letterSpacing: "-0.01em",
            fontWeight: "700",
          },
        ],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
